// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeruj15rjqzxODw0GFtpcaNVm-raVO_6U',
    appId: '1:647579700830:web:a6a8a1b8e77fd7a2c22ecf',
    messagingSenderId: '647579700830',
    projectId: 'horizon-315bd',
    authDomain: 'horizon-315bd.firebaseapp.com',
    databaseURL: 'https://horizon-315bd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'horizon-315bd.appspot.com',
    measurementId: 'G-YELNQJ5C2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJe5pb7wP_83N7KdBdd9eePAJGiAbzj10',
    appId: '1:647579700830:android:c7452701069797b3c22ecf',
    messagingSenderId: '647579700830',
    projectId: 'horizon-315bd',
    databaseURL: 'https://horizon-315bd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'horizon-315bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnEKkqplXV8boBxiyQQ5kBydt38b9qqjw',
    appId: '1:647579700830:ios:8689059fec87240bc22ecf',
    messagingSenderId: '647579700830',
    projectId: 'horizon-315bd',
    databaseURL: 'https://horizon-315bd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'horizon-315bd.appspot.com',
    iosClientId: '647579700830-peoo6hg7i0cvhlb5040l6n0mq8nch7h5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnEKkqplXV8boBxiyQQ5kBydt38b9qqjw',
    appId: '1:647579700830:ios:8689059fec87240bc22ecf',
    messagingSenderId: '647579700830',
    projectId: 'horizon-315bd',
    databaseURL: 'https://horizon-315bd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'horizon-315bd.appspot.com',
    iosClientId: '647579700830-peoo6hg7i0cvhlb5040l6n0mq8nch7h5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeruj15rjqzxODw0GFtpcaNVm-raVO_6U',
    appId: '1:647579700830:web:5410cc69706587d0c22ecf',
    messagingSenderId: '647579700830',
    projectId: 'horizon-315bd',
    authDomain: 'horizon-315bd.firebaseapp.com',
    databaseURL: 'https://horizon-315bd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'horizon-315bd.appspot.com',
    measurementId: 'G-EB9ZMVBW1W',
  );

}