# Use the official Flutter image
FROM cirrusci/flutter:stable

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY frontend/flutter_app/ .

# Get Flutter dependencies
RUN flutter pub get

# Build the Flutter app
RUN flutter build web

# Expose port 80
EXPOSE 80

# Serve the Flutter app
CMD ["flutter", "build", "web", "--release"]
